version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/sqleech
    binary: sqleech
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/0x6d61/sqleech/internal/cli.version={{.Version}}
      - -X github.com/0x6d61/sqleech/internal/cli.commit={{.Commit}}
      - -X github.com/0x6d61/sqleech/internal/cli.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
